pipeline {
    agent none
    stages {
        stage('Install Docker') {
            steps {
                sh '''
                    apt-get update -y
                    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
                    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
                    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
                    apt-get update -y
                    apt-get install -y docker-ce docker-ce-cli containerd.io
                    usermod -aG docker jenkins || true
                    echo ">>> Docker installed successfully"
                    '''
                    }
                }
            }
    stages {
        stage('Build') {
                agent {
                    docker {
                        image 'maven:3.8.7-openjdk-17'   // Official Maven + JDK image
                        args '-v /root/.m2:/root/.m2'   // Cache Maven repo for faster builds
                    }
                }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
