pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    tools {
        // This section declares the Maven tool to be used in the pipeline.
        // The 'M3' here must match the name configured in Global Tool Configuration.
        maven 'M3' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
