pipeline {
    agent {
            docker {
                image 'maven:3.8.7-eclipse-temurin-17'   // Official Maven + JDK image
                args '-v /root/.m2:/root/.m2'   // Cache Maven repo for faster builds
            }
        }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
